name: Deploy to InfinityFree via FTP

on:
  push:
    branches: [ "main" ]   # change this if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftpupload.net
          username: if0_40505763
          password: sj0JJPSTYXf7
          local-dir: "./"
          server-dir: "/htdocs/"
